apiVersion: v1
kind: Service
metadata:
  name: {{ include "shirchart.fullname" .}}
spec:
  selector:
    {{ include "shirchart.selectorLabels" . | nindent 4}}
  ports:
  - port: {{.Values.service.port}}
    targetPort: {{.Values.service.targetPort}}
